apiVersion: v1
kind: Pod
metadata:
  name: cron
spec:
  containers:
  - name: repl
    image: kloiadocker/kubevirt-migrator:0.0.2
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    command:
    - /bin/sh
    - -c
    - sleep infinity
    #- "mkdir /data/dimg /data/dfs /data/sfs/; sshfs -o StrictHostKeyChecking=no -o port=31774 10.0.11.240:/data/simg /data/dimg; guestmount -a /data/simg/disk.img -m /dev/sda4 --ro /data/sfs; guestmount -a /data/dimg/disk.img -m /dev/sda4 --rw /data/dfs; rclone sync --progress /data/sfs/ /data/dfs/ --skip-links; sleep infinity"
    resources:
      limits:
        cpu: 1
        memory: 2Gi
    volumeMounts:
    - mountPath: /data/simg
      name: rootdisk
      readOnly: true
    - mountPath: /root/.ssh
      name: ssh
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: default-dockercfg-w7wn8
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-labeller.kubevirt.io/obsolete-host-model
            operator: DoesNotExist
  nodeSelector:
    kubernetes.io/arch: amd64
    kubevirt.io/schedulable: "true"
  volumes:
  - name: rootdisk
    persistentVolumeClaim:
      claimName: rhel9-test-3
  - name: ssh
    secret:
      secretName: rhel9-test-3-repl-ssh-keys
      defaultMode: 0400