apiVersion: v1
kind: Service
metadata:
  labels:
    app: rhel9-test-17-dst-replicator
  name: rhel9-test-17-dst-svc
spec:
  ports:
    - port: 22
  selector:
    app: rhel9-test-17-dst-replicator
  type: NodePort
