apiVersion: batch/v1
kind: CronJob
metadata:
  name: rhel9-test-22-repl-cronjob
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: repl
              image: kloiadocker/kubevirt-migrator:0.0.2
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
              resources:
                requests:
                  cpu: 1000m
                  memory: 2Gi
              command:
                - /bin/sh
                - -c
                - "mkdir /data/dimg /data/dfs /data/sfs/; sshfs -o StrictHostKeyChecking=no -o port=31951 10.1.80.249:/data/simg /data/dimg; guestmount -a /data/simg/disk.img -m /dev/sda4 --ro /data/sfs; guestmount -a /data/dimg/disk.img -m /dev/sda4 --rw /data/dfs; rclone sync --progress /data/sfs/ /data/dfs/ --skip-links --checkers 8 --contimeout 100s --timeout 300s --retries 3 --low-level-retries 10 --drive-acknowledge-abuse --stats 1s --cutoff-mode=soft; sleep 20"
              volumeMounts:
                - mountPath: /data/simg
                  name: rootdisk
                  readOnly: true
                - mountPath: /root/.ssh
                  name: ssh
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: rootdisk
              persistentVolumeClaim:
                claimName: rhel9-test-22
            - name: ssh
              secret:
                secretName: rhel9-test-22-repl-ssh-keys
                defaultMode: 0400
