apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ${VM_NAME}-dst-replicator
  name: ${VM_NAME}-dst-replicator
spec:
  containers:
    - image: kloiadocker/ssh-server
      name: dst-repl
      resources:
        limits:
          cpu: 1
          memory: 2Gi
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /data/simg
          name: rootdisk
  restartPolicy: Always
  volumes:
    - name: rootdisk
      persistentVolumeClaim:
        claimName: ${VM_NAME}
