apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ${VM_NAME}-src-replicator
  name: ${VM_NAME}-src-replicator
spec:
  containers:
    - image: kloiadocker/kubevirt-migrator:0.0.2
      name: src-repl
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        requests:
          cpu: ${CPU_REQUEST}
          memory: ${MEMORY_REQUEST}
      securityContext:
        privileged: true
      command:
        - /bin/sh
        - -c
        - sleep infinity
      volumeMounts:
        - mountPath: /data/simg
          name: rootdisk
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
    - name: default-dockercfg-w7wn8
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-labeller.kubevirt.io/obsolete-host-model
                operator: DoesNotExist
  nodeSelector:
    kubernetes.io/arch: amd64
    kubevirt.io/schedulable: "true"
  volumes:
    - name: rootdisk
      persistentVolumeClaim:
        claimName: ${VM_NAME}
