apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${VM_NAME}-repl-cronjob
  namespace: ${NAMESPACE}
spec:
  schedule: "${SCHEDULE}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: repl
              image: kloiadocker/kubevirt-migrator:0.0.2
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
              resources:
                requests:
                  cpu: 1000m
                  memory: 2Gi
              command:
                - /bin/sh
                - -c
                - "${REPLICATION_COMMAND}"
              volumeMounts:
                - mountPath: /data/simg
                  name: rootdisk
                  readOnly: true
                - mountPath: /root/.ssh
                  name: ssh
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: rootdisk
              persistentVolumeClaim:
                claimName: ${VM_NAME}
            - name: ssh
              secret:
                secretName: ${VM_NAME}-repl-ssh-keys
                defaultMode: 0400
