apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${VM_NAME}-repl-cronjob
  namespace: ${NAMESPACE}
spec:
  schedule: "${SCHEDULE}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: repl
              image: kloiadocker/kubevirt-migrator:0.0.2
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              command:
                - /bin/bash
                - -c
                - |
                  echo "${REPLICATION_COMMAND}" | base64 -d | /bin/bash
              volumeMounts:
                - mountPath: /data/simg
                  name: rootdisk
                  readOnly: true
                - mountPath: /root/.ssh
                  name: ssh
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: rootdisk
              persistentVolumeClaim:
                claimName: ${VM_NAME}
            - name: ssh
              secret:
                secretName: ${VM_NAME}-repl-ssh-keys
                defaultMode: 0400
